name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - name: check out
            uses: actions/checkout@v2
            with:
                 repository: ${{GITHUB_ACTION_REPOSITORY}} 
                 ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: submodule update
            run: git submodule update --init --recursive
          - name: full_test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: web-factory-
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            uses: webfactory/ssh-agent@v0.5.3
          - name: Cleanup
            if: always()
            run: 
              ssh-add -D

